/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.government.governmentMayor;

import business.enterprise.Enterprise;
import business.enterprise.DairyEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.role.Role;
import business.userAccount.UserAccount;
import business.workQueue.CollectionWorkRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


public class GovernmentMayorViewWastageAvoidedByDairyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Network network;

    /**
     * Creates new form GovernmentMayorViewWastageAvoidedByDairyJPanel
     */
    public GovernmentMayorViewWastageAvoidedByDairyJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        populateDairyCombo();
        populateData(null);  
        
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblDairy = new javax.swing.JLabel();
        cmbDairy = new javax.swing.JComboBox();
        jScrollPane = new javax.swing.JScrollPane();
        tblWastageAvoided = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        lblTotalWastage = new javax.swing.JLabel();
        lblWastageValue = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setText("Mayor Work Area - View Dairy Wastage Avoided");

        lblDairy.setText("Dairy :");

        cmbDairy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDairyActionPerformed(evt);
            }
        });

        tblWastageAvoided.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dairy Name", "Wastage Avoided(in pounds)", "Status", "NGO delivered to"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tblWastageAvoided);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDetails.setText("View Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        lblTotalWastage.setText("Total Wastage Avoided:");

        lblWastageValue.setText("<wastage>");

        btnExport.setText("Export Data");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDairy, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDairy, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(290, 290, 290)
                                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTotalWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWastageValue, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblHeading)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDairy)
                    .addComponent(cmbDairy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalWastage)
                    .addComponent(lblWastageValue))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetails)
                    .addComponent(btnBack)
                    .addComponent(btnExport))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDairyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDairyActionPerformed
        // TODO add your handling code here:
        if (cmbDairy.getSelectedIndex() < 1) {
            populateData(null);
        } else {
            DairyEnterprise e = (DairyEnterprise) cmbDairy.getSelectedItem();
            populateData(e);
        }
    }//GEN-LAST:event_cmbDairyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWastageAvoided.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,
                "Please select a request item to view details",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            CollectionWorkRequest request = (CollectionWorkRequest) tblWastageAvoided.getValueAt(selectedRow, 2);

            GovernmentMayorViewRequestDetailsJPanel governmentMayorViewRequestDetailsJPanel = new GovernmentMayorViewRequestDetailsJPanel(userProcessContainer, request);
            userProcessContainer.add("GovernmentMayorViewRequestDetailsJPanel", governmentMayorViewRequestDetailsJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblWastageAvoided.getModel();
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet worksheet = workbook.createSheet();

        TreeMap<String, Object[]> dataMap = new TreeMap<>();
        dataMap.put("0", new Object[]{
            dtm.getColumnName(0), dtm.getColumnName(1), dtm.getColumnName(2), dtm.getColumnName(3)
        });

        for (int i = 0; i < dtm.getRowCount(); i++) {
            dataMap.put(i + 1 + "", new Object[]{
                dtm.getValueAt(i, 0).toString(),
                dtm.getValueAt(i, 1).toString(),
                dtm.getValueAt(i, 2).toString(),
                dtm.getValueAt(i, 3).toString()
            });
        }

        Set<String> ids = dataMap.keySet();
        XSSFRow row;
        int rowId = 0;

        XSSFCellStyle style = workbook.createCellStyle();
        XSSFFont font = workbook.createFont();
        font.setBoldweight(XSSFFont.BOLDWEIGHT_BOLD);
        style.setFont(font);

        for (String key : ids) {
            row = worksheet.createRow(rowId++);

            Object[] values = dataMap.get(key);

            int cellId = 0;
            for (Object o : values) {
                Cell cell = row.createCell(cellId++);
                cell.setCellValue((String) o);
                if (rowId== 1) {
                    cell.setCellStyle(style);
                }
            }
        }

        try {
            String date = new SimpleDateFormat("MM_dd_yyyy_HH_mm_ss").format(new Date());
            String fileName = "Mayor_" + network.getName() + "_" + date + ".xlsx";
            FileOutputStream fos = new FileOutputStream(new File(System.getProperty("user.home") + "/Desktop/"+fileName));
            workbook.write(fos);
            fos.close();
            JOptionPane.showMessageDialog(null, "Data exported to excel");
        } catch (FileNotFoundException fnfe) {
            // File Not Found
        } catch (IOException iex) {
            // IO Exception block
        }
    }//GEN-LAST:event_btnExportActionPerformed

     public void populateDairyCombo() {
        cmbDairy.removeAllItems();
        cmbDairy.addItem(null);
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e.getEnterpriseType() == Enterprise.EnterpriseType.Dairy) {
                cmbDairy.addItem(e);
            }
        }
    }

    public void populateData(DairyEnterprise dairy) {

        DefaultTableModel dtm = (DefaultTableModel) tblWastageAvoided.getModel();
        dtm.setRowCount(0);

        double wastage = 0;

        // All data
        if (dairy == null) {

            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Dairy) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                            if ((ua.getRole().getRoleType().getValue()).equals(Role.RoleType.DairyWorker.getValue())) {
                                for (WorkRequest wr : ua.getWorkQueue().getWorkRequestList()) {
                                    if (wr instanceof CollectionWorkRequest) {
                                        CollectionWorkRequest cwr = (CollectionWorkRequest) wr;

                                        Object row[] = new Object[4];
                                        row[0] = cwr.getRaisedByDairy();
                                        row[1] = cwr.getTotalQuantity();
                                        row[2] = cwr;
                                        row[3] = cwr.getDeliverToNGO() == null ? "Undelivered" : cwr.getDeliverToNGO();
                                        dtm.addRow(row);

                                        wastage += cwr.getTotalQuantity();
                                    }
                                }
                            }
                        }
                    }
                }
            }

        } // Filtered
        else {

            for (Organization o : dairy.getOrganizationDirectory().getOrganizationList()) {
                for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                    if ((ua.getRole().getRoleType().getValue()).equals(Role.RoleType.DairyWorker.getValue())) {
                        for (WorkRequest wr : ua.getWorkQueue().getWorkRequestList()) {
                            CollectionWorkRequest cwr = (CollectionWorkRequest) wr;

                            Object row[] = new Object[4];
                            row[0] = cwr.getRaisedByDairy();
                            row[1] = cwr.getTotalQuantity();
                            row[2] = cwr;
                            row[3] = cwr.getDeliverToNGO() == null ? "Undelivered" : cwr.getDeliverToNGO();
                            dtm.addRow(row);

                            wastage += cwr.getTotalQuantity();
                        }
                    }
                }
            }

        }

        lblWastageValue.setText(wastage + " pounds");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnExport;
    private javax.swing.JComboBox cmbDairy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblDairy;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblTotalWastage;
    private javax.swing.JLabel lblWastageValue;
    private javax.swing.JTable tblWastageAvoided;
    // End of variables declaration//GEN-END:variables
}
