
package userInterface.government.governmentMayor;

import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class GovernmentMayorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Network network;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public GovernmentMayorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        lblValue.setText(lblValue.getText() + " " + account.getEmployee().getName());

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnWastageAvoided = new javax.swing.JButton();
        btnPeopleFed = new javax.swing.JButton();
        btnWastageAvoidedChart = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));

        lblHeading.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setText("Mayor Work Area");

        lblValue.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblValue.setForeground(new java.awt.Color(255, 255, 255));
        lblValue.setText("Welcome, ");

        btnWastageAvoided.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/government/governmentMayor/viewitem.png"))); // NOI18N
        btnWastageAvoided.setText("View Wastage Avoided by Dairy(Tabular)");
        btnWastageAvoided.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWastageAvoidedActionPerformed(evt);
            }
        });

        btnPeopleFed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/government/governmentMayor/viewitem.png"))); // NOI18N
        btnPeopleFed.setText("View People Fed by NGOs");
        btnPeopleFed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeopleFedActionPerformed(evt);
            }
        });

        btnWastageAvoidedChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/government/governmentMayor/viewitem.png"))); // NOI18N
        btnWastageAvoidedChart.setText("View Wastage Avoided by Dairy(Chart)");
        btnWastageAvoidedChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWastageAvoidedChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnWastageAvoided, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWastageAvoidedChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPeopleFed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblHeading)
                .addGap(50, 50, 50)
                .addComponent(lblValue)
                .addGap(49, 49, 49)
                .addComponent(btnWastageAvoided)
                .addGap(24, 24, 24)
                .addComponent(btnWastageAvoidedChart)
                .addGap(42, 42, 42)
                .addComponent(btnPeopleFed)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeopleFedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeopleFedActionPerformed

        GovernmentMayorViewNGODataJPanel governmentMayorViewPeopleFedJPanel = new GovernmentMayorViewNGODataJPanel(userProcessContainer, network);
        userProcessContainer.add("GovernmentMayorViewPeopleFedJPanel", governmentMayorViewPeopleFedJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnPeopleFedActionPerformed

    private void btnWastageAvoidedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWastageAvoidedActionPerformed

        GovernmentMayorViewWastageAvoidedByDairyJPanel governmentMayorViewWastageAvoidedByDairy = new GovernmentMayorViewWastageAvoidedByDairyJPanel(userProcessContainer, network);
        userProcessContainer.add("GovernmentMayorViewWastageAvoidedByDairy", governmentMayorViewWastageAvoidedByDairy);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWastageAvoidedActionPerformed

    private void btnWastageAvoidedChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWastageAvoidedChartActionPerformed
        // TODO add your handling code here:
        GovernmentMayorViewChartJPanel governmentMayorViewChart = new GovernmentMayorViewChartJPanel(userProcessContainer, network);
        userProcessContainer.add("GovernmentMayorViewChart", governmentMayorViewChart);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWastageAvoidedChartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeopleFed;
    private javax.swing.JButton btnWastageAvoided;
    private javax.swing.JButton btnWastageAvoidedChart;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables

}
